name: Generate YouTube RSS Feed for my subscriptions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # runs every hour

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run feed.py
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        run: |
          python feed.py

      - name: Upload generated feed.xml as artifact
        uses: actions/upload-artifact@v3
        with:
          name: feed-xml
          path: feed.xml
